[build]
	publish = "out/"
	command = "./scripts/build-release"

[build.environment]
	NODE_VERSION = "16"
	NETLIFY_NEXT_PLUGIN_SKIP = "true"
	NEXT_PUBLIC_DOMAIN_URL = "https://cert-manager.io"

[context.production.environment]
	NEXT_PUBLIC_ENABLE_ANALYTICS = "true"
	NEXT_PUBLIC_DOCS_SEARCH_APP_ID = "01YP6XYAE7"
	NEXT_PUBLIC_DOCS_SEARCH_INDEX_NAME = "cert-manager"
	NEXT_PUBLIC_DOMAIN_URL = "https://cert-manager.io"
