[build]
	publish = "out/"
	command = "./scripts/build-release"

[build.environment]
	NODE_VERSION = "16"
	NETLIFY_NEXT_PLUGIN_SKIP = "true"

[context.production.environment]
	NEXT_PUBLIC_ENABLE_ANALYTICS = "true"
